services:
  - type: web
    name: queen-nicky-md
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: OWNER_NAME
        value: OWNER
      - key: OWNER_NUMBER
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SESSION_ID
        sync: false
      - key: PREFIX
        value: .
      - key: BOT_NAME
        value: QUEEN NICKY MD
      - key: PACK_INFO
        value: OWNER;QUEEN NICKY MD
      - key: WORKTYPE
        value: public
      - key: THEME
        value: QUEEN-NICKY
